//
//  LocalityModel.swift
//  DVTWeatherApp
//
//  Created by Bonginkosi Tshabalala on 2024/06/14.
//
//List of towns in South Africa: https://academickids.com/encyclopedia/index.php/List_of_towns_in_South_Africa

import Foundation

struct LocalCityName {
  let name: String
}

struct LocalCities {
  let localCities: [LocalCityName] = [
    LocalCityName(name: "Adelaide"),
    LocalCityName(name: "Alexander Bay"),
    LocalCityName(name: "Aliwal North"),
    LocalCityName(name: "Alberton"),
    LocalCityName(name: "Allanridge"),
    LocalCityName(name: "Amersfoort"),
    LocalCityName(name: "Amsterdam"),
    LocalCityName(name: "Askham"),
    LocalCityName(name: "Ballito"),
    LocalCityName(name: "Barkly East"),
    LocalCityName(name: "Benoni"),
    LocalCityName(name: "Bethal"),
    LocalCityName(name: "Bethlehem"),
    LocalCityName(name: "Bisho"),
    LocalCityName(name: "Boksburg"),
    LocalCityName(name: "Botshabelo"),
    LocalCityName(name: "Bronkhorstspruit"),
    LocalCityName(name: "Brakpan"),
    LocalCityName(name: "Brandfort"),
    LocalCityName(name: "Brits"),
    LocalCityName(name: "Britstown"),
    LocalCityName(name: "Bultfontein"),
    LocalCityName(name: "Carletonville"),
    LocalCityName(name: "Carolina"),
    LocalCityName(name: "Centurion"),
    LocalCityName(name: "Clarens"),
    LocalCityName(name: "Colenso"),
    LocalCityName(name: "Cullinan"),
    LocalCityName(name: "Daveyton"),
    LocalCityName(name: "De Aar"),
    LocalCityName(name: "Delmas"),
    LocalCityName(name: "Deneysville"),
    LocalCityName(name: "Dullstroom"),
    LocalCityName(name: "Dundee"),
    LocalCityName(name: "Edenburg"),
    LocalCityName(name: "Edenvale"),
    LocalCityName(name: "Empangeni"),
    LocalCityName(name: "Ermelo"),
    LocalCityName(name: "Eshowe"),
    LocalCityName(name: "Ficksburg"),
    LocalCityName(name: "Frankfort"),
    LocalCityName(name: "George"),
    LocalCityName(name: "Germiston"),
    LocalCityName(name: "Graaff-Reinet"),
    LocalCityName(name: "Grahamstown"),
    LocalCityName(name: "Hammanskraal"),
    LocalCityName(name: "Harrismith"),
    LocalCityName(name: "Heidelberg"),
    LocalCityName(name: "Heilbron"),
    LocalCityName(name: "Hermanus"),
    LocalCityName(name: "Hibberdene"),
    LocalCityName(name: "Hillcrest"),
    LocalCityName(name: "Inanda"),
    LocalCityName(name: "Kempton Park"),
    LocalCityName(name: "Klerksdorp"),
    LocalCityName(name: "Knysna"),
    LocalCityName(name: "Kokstad"),
    LocalCityName(name: "Krugersdorp"),
    LocalCityName(name: "KwaDukuza"),
    LocalCityName(name: "KwaMashu"),
    LocalCityName(name: "KwaMhlanga"),
    LocalCityName(name: "Kwa-Thema"),
    LocalCityName(name: "Lenasia"),
    LocalCityName(name: "Lephalale"),
    LocalCityName(name: "Lichtenburg"),
    LocalCityName(name: "Lydenburg"),
    LocalCityName(name: "Mafikeng"),
    LocalCityName(name: "Makhado"),
    LocalCityName(name: "Malelane"),
    LocalCityName(name: "Mamelodi"),
    LocalCityName(name: "Mandini"),
    LocalCityName(name: "Mangaung"),
    LocalCityName(name: "Margate"),
    LocalCityName(name: "Matatiele"),
    LocalCityName(name: "Middelburg"),
    LocalCityName(name: "Midrand"),
    LocalCityName(name: "Mokopane"),
    LocalCityName(name: "Mtubatuba"),
    LocalCityName(name: "Nelspruit"),
    LocalCityName(name: "Newcastle"),
    LocalCityName(name: "Nigel"),
    LocalCityName(name: "Odendaalsrus"),
    LocalCityName(name: "Orkney"),
    LocalCityName(name: "Paarl"),
    LocalCityName(name: "Phuthaditjhaba"),
    LocalCityName(name: "Pinetown"),
    LocalCityName(name: "Plettenberg Bay"),
    LocalCityName(name: "Polokwane"),
    LocalCityName(name: "Port Shepstone"),
    LocalCityName(name: "Queensburgh"),
    LocalCityName(name: "Randburg"),
    LocalCityName(name: "Randfontein"),
    LocalCityName(name: "Richards Bay"),
    LocalCityName(name: "Roodepoort"),
    LocalCityName(name: "Rustenburg"),
    LocalCityName(name: "Sandton"),
    LocalCityName(name: "Sasolburg"),
    LocalCityName(name: "Scottburgh"),
    LocalCityName(name: "Secunda"),
    LocalCityName(name: "Senekal"),
    LocalCityName(name: "Soweto"),
    LocalCityName(name: "Springs"),
    LocalCityName(name: "Standerton"),
    LocalCityName(name: "Stellenbosch"),
    LocalCityName(name: "Tembisa"),
    LocalCityName(name: "Thabazimbi"),
    LocalCityName(name: "Thohoyandou"),
    LocalCityName(name: "Tongaat"),
    LocalCityName(name: "Ulundi"),
    LocalCityName(name: "Umlazi"),
    LocalCityName(name: "Umzinto"),
    LocalCityName(name: "Upington"),
    LocalCityName(name: "Vanderbijlpark"),
    LocalCityName(name: "Vereeniging"),
    LocalCityName(name: "Virginia"),
    LocalCityName(name: "Vryburg"),
    LocalCityName(name: "Vryheid"),
    LocalCityName(name: "Welkom"),
    LocalCityName(name: "Westonaria"),
    LocalCityName(name: "Witbank"),
    LocalCityName(name: "Zeerust")
  ]
}
